### ISSUE TITLE
Improve export stuff

### ISSUE THREAD

**Issue by Yu-Dylan** [opalarchive/opal#26]
Specifically for transferring to database.sty. The layout:
`\entry[tags={tag1,tag2},title={title},problem={
problem
},solution={
solution
}]{}`
The {} at the end I'm still debating what to include. Maybe walkthrough but IDK yet.

Also: export to tex file is also cool.

**Comment by AmoleR** [comment]
Closing this issue.

OPAL will have an export to plain text feature, using our [parser](https://www.github.com/opalarchive/parser), you'll be able to convert BBCode into whatever language you desire.

In addition, we'll allow for some minimal scripts to run, which should allow you to format the issue.
