### ISSUE TITLE
[Alpha] Key features missing from the problem management system

### ISSUE THREAD

**Issue by cosmicgenius** [opalarchive/opal#3]
Check off items when complete and mention this issue in the commit
- General:
  - [x] Add problem
  - [x] Searching (by keyword, author, title, tag, author, category, difficulty slider) and sorting (by difficulty, index, votes)
  - [x] Navigation for different pages
- Details page:
  - [x] Solution writing
  - [x] Edit problem and edit reply
- Unconfigured page:
  - [x] @AmoleR should be working on it (stepper)
- Compilation page:
  - [x] Create the page: owner (users? admins?) should be able to create compilations (perhaps some type of advanced [transfer list](https://material-ui.com/components/transfer-list/))
- Settings page:
  - [x] Create the page (admin/owner only)

Edit: moved less important changes to the beta issue.

**Comment by nhshah15** [comment]
I think I'll do the front end for the compilation page tomorrow morning? Will take a look at this more thoroughly but I'll try to contribute some of the front end code within the next like week.

**Comment by cosmicgenius** [comment]
Rate limiting moved to beta (#6) and config change moved to far future (maybe I will put this on beta later).

**Comment by cosmicgenius** [comment]
Change project name moved to beta #6. Issue is now considered complete.
